alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias ip="ip -color=auto"
alias diff="diff --color=auto"

alias yarn="yarn --use-yarnrc \"\$XDG_CONFIG_HOME/yarn/config\""
alias wget="wget --hsts-file=\"\$XDG_DATA_HOME/wget-hsts\""
alias nvidia-settings="nvidia-settings --config=\"\$XDG_CONFIG_HOME\"/nvidia/settings"

alias config="/usr/bin/git --git-dir=\$HOME/.dotfiles/ --work-tree=\$HOME"
